apps/demo/urls.py
from django.urls import path, include
from apps.demo.views import (login, main,)

app_name = 'demo'

urlpatterns = [
    path('', login, name='login'),
    path('main/', main, name='main'),

]

pea/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.demo.urls')),
]

apps/demo/models.py
from django.db import models

# Create your models here.

apps/demo/views.py
from django.shortcuts import render
from .choices import (get_pea,)

def login(request):
	return render(request, 'login.html')

def main(request):
	context = get_pea()
	return render(request, 'main.html', context)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>DT-DATA</title>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'img/logo.png' %}"/>
    <link href="{% static 'vendor/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'vendor/chartsjs/Chart.min.css' %}" rel="stylesheet"> -->
    <link href="{% static 'vendor/flagiconcss3/css/flag-icon.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/master.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
</head>
<body>
	<div class="wrapper">
		{% block nav %}
			{% include 'base/partials/nav.html' %}
		{% endblock %}

		<div id="body" class="active">
			{% include 'base/partials/topnav.html' %}
            <div class="content">
				{% block content %}
				{% endblock %}
            </div>
		</div>

	</div>
	<script src="{% static 'vendor/jquery3/jquery.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap4/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor/fontawesome5/js/solid.min.js' %}"></script>
	<script src="{% static 'vendor/fontawesome5/js/fontawesome.min.js' %}"></script>
	<!-- <script src="{% static 'vendor/chartsjs/Chart.min.js' %}"></script> -->
    <script src="{% static 'vendor/notyfy/notify.min.js' %}"></script>
    
    {% block js %}
		<script src="{% static 'js/ui/dashboard-charts.js' %}"></script>
    {% endblock %}
    
    {% block script %}
	<script src="{% static 'js/ui/script.js' %}"></script>
    {% endblock %}

    <script type="text/javascript">
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
        $('#body').toggleClass('active');
    });
    {% if alert %}
        $.notify("{{alert}}", {'position':'right-bottom', 'className':'success'});
    {% endif %}
    </script>
    <script src="{% static 'js/basics.js' %}"></script>
</body>
</html>

templates/base/partials/nav.html
{% load static %}
<nav id="sidebar">
    <div class="sidebar-header ">
        <img src="{% static 'img/logo.png' %}" alt="dt-data logo" class="main-logo">
    </div>
    <ul class="list-unstyled components text-secondary nav-tabs">
        <li class="nav-link {% if dashboard %}active{% endif %}">
            <a href="{% url 'demo:main' %}"><i class="fas fa-chart-bar"></i> Dashboard</a>
        </li>
    </ul>
</nav>

templates/base/partials/topnav.html
<nav class="navbar navbar-expand-lg navbar-white bg-white">
    <button type="button" id="sidebarCollapse" class="btn btn-outline-secondary default-secondary-menu">
        <i class="fas fa-bars"></i><span></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <div class="nav-dropdown">
                    <a href="" class="nav-item nav-link dropdown-toggle text-secondary" data-toggle="dropdown"><i class="fas fa-user"></i> <span>Luis Quiroz</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i></a>
                    <div class="dropdown-menu dropdown-menu-right nav-link-menu">
                        <ul class="nav-list">
                            <li><a href="" class="dropdown-item"><i class="fas fa-address-card"></i> Profile</a></li>
                            <li><a href="" class="dropdown-item"><i class="fas fa-envelope"></i> Messages</a></li>
                            <li><a href="" class="dropdown-item"><i class="fas fa-cog"></i> Settings</a></li>
                            <div class="dropdown-divider"></div>
                            <li><a href="{% url 'demo:login' %}" class="dropdown-item"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>DT-DATA</title>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'img/logo.png' %}"/>
    <link href="{% static 'vendor/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/auth.css' %}" rel="stylesheet">
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
</head>
<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <img class="brand main-logo" src="{% static 'img/logo.png' %}" alt="DT-Data" width="100%">
                    </div>
                    <h6 class="mb-4 text-muted">DT-DATA - PEA</h6>
                    <form action="" method="">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email" required>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Password" required>
                        </div>
                        <div class="form-group text-left">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" name="remember" class="custom-control-input" id="remember-me">
                                <label class="custom-control-label" for="remember-me">Recuerdame</label>
                            </div>
                        </div>
                        <a href="{% url 'demo:main' %}" class="btn btn-primary shadow-2 mb-4 text-white" >Ingresar</a>
                        <!-- <a href="{# url 'index' #}" class="btn btn-primary shadow-2 mb-4 text-white" >Ingresar</a> -->
                    </form>
                    <p class="mb-2 text-muted">¿Olvidaste tu Contraseña? <a href="#">Recuperar</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'vendor/jquery3/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap4/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/main.html
{% extends 'base/base.html' %}

{% block content %}
	<div class="container-fluid">
		<h5>PEA 2021 (BUDGET)</h5>
		<div class="row">
			<div class="col-md-12">
				{% include 'partials/_pea_table.html' %}
			</div>
		</div>
	</div>
{% endblock %}

{% block js %}
{% endblock %}

templates/partials/_pea_table.html
{% load demo_tags %}
<table class="table table-sm text-center">
	<thead>
		<tr>
			<th colspan="16">INCOME STATEMENT</th>
		</tr>
	</thead>
	<tbody>
		{% for cat in categories %}
			<tr class="bg-info text-white">
				<td><strong>{{cat}}</strong></td>
				{% for m in months %}
				<td>{{m}}</td>
				{% endfor %}
				<td>2021</td>
				<td class="bg-secondary">2020</td>
				<td class="bg-white text-primary"><strong>Variability</strong></td>
			</tr>
			{% for ins in income_statement|key:cat %}
				<tr>
					<td>{{ins.1}}</td>
					{% for m in months %}
					<td>{% get_data report m cat ins.1 %}</td>
					{% endfor %}
					<td class="text-danger">{% get_total_income_statement report ins.1 %}</td>
					<td class="text-secondary">{% get_last_totals last_totals ins.1 %}</td>
					<td class="bg-white text-{% get_var_income_statement_class report last_totals ins.1 %} text-white">{% get_var_income_statement report last_totals ins.1 %}</td>
				</tr>
			{% endfor %}
			<tr>
				<td><strong>Total {{ cat|title }}</strong></td>
				{% for m in months %}
				<td>{% get_total_month report m cat %}</td>
				{% endfor %}
				<td><strong>{% get_total_category report cat %}</strong></td>
				<td class="text-secondary"><strong>{% get_last_totals_category last_totals cat %}</strong></td>
				<td class="text-{% get_var_total_category_class report cat last_totals %} bg-white"><strong>{% get_var_total_category report cat last_totals %}</strong></td>
			</tr>
		{% endfor %}
		<tr class="bg-success text-white">
			<td>Margen Operativo</td>
			{% for m in months %}
			<td class="bg-{% get_operating_margin_class report m %}">{% get_operating_margin report m %}</td>
			{% endfor %}
			<td>{% get_total_operating_margin report %}</td>
			<td class="bg-secondary">{% get_last_totals_operating_margin last_totals %}</td>
			<td class="bg-white text-{% get_var_last_totals_operating_margin_class report last_totals %}">{% get_var_last_totals_operating_margin report last_totals %}</td>
		</tr>
		<tr class="bg-primary text-white">
			<td>EBITDA</td>
			{% for m in months %}
			<td class="bg-{% get_ebitda_class report ebitda m %}">{% get_ebitda report ebitda m %}</td>
			{% endfor %}
			<td>{% get_total_ebitda report ebitda months %}</td>
			<td class="bg-secondary">{{last_ebdita|coma}}</td>
			<td class="bg-white text-{% get_var_total_ebitda_class report ebitda months last_ebdita %}">{% get_var_total_ebitda report ebitda months last_ebdita %}</td>
		</tr>
		<tr>
			<td colspan="16">EBITDA%</td>
		</tr>
		{% for item in ebitda_names %}
		<tr>
			<td class="text-nowrap">{{item}}</td>
			{% for m in months %}
			<td>{% get_ebitda_item ebitda m item %}</td>
			{% endfor %}
			<td>{% get_total_ebitda_item ebitda item %}</td>
			<td class="text-secondary">{{last_ebdita_totals|key:item}}</td>
			<td class="bg-white text-{% get_var_total_ebitda_item_class ebitda last_ebdita_totals item %}">{% get_var_total_ebitda_item ebitda last_ebdita_totals item %}</td>
		</tr>
		{% endfor %}
		<tr><td colspan="16"><br></td></tr>
		<tr class="font-weight-bold">
			<td>INCOME BEFORE TAX</td>
			{% for m in months %}
			<td>{% get_income_before_tax report ebitda m %}</td>
			{% endfor %}
			<td>{% get_total_income_before_tax report ebitda months %}</td>
			<td class="text-secondary">{{last_ebdita_totals|key:'income'}}</td>
			<td class="bg-white text-{% get_var_total_income_before_tax_class report ebitda months last_ebdita_totals %}">{% get_var_total_income_before_tax report ebitda months last_ebdita_totals %}</td>
		</tr>
		<tr class="font-weight-bold">
			<td>IVA Tax</td>
			{% for m in months %}
			<td>{% get_data_by_moth iva m %}</td>
			{% endfor %}
			<td>{{total_iva|coma}}</td>
			<td class="text-secondary">{{last_ebdita_totals|key:'iva'}}</td>
			<td class="bg-white text-{% substraction_class total_iva last_ebdita_totals|key:'iva' %}">{% substraction total_iva last_ebdita_totals|key:'iva' %}</td>
		</tr>
		<tr class="font-weight-bold">
			<td>Rent Tax</td>
			{% for m in months %}
			<td>{% get_data_by_moth rent m %}</td>
			{% endfor %}
			<td>{{total_rent|coma}}</td>
			<td class="text-secondary">{{last_ebdita_totals|key:'rent'}}</td>
			<td class="bg-white text-{% substraction_class total_rent last_ebdita_totals|key:'rent' %}">{% substraction total_rent last_ebdita_totals|key:'rent' %}</td>
		</tr>
		<tr class="bg-dark text-white">
			<td>NET INCOME</td>
			{% for m in months %}
			<td class="bg-{% get_income_class report ebitda iva rent m %}">{% get_income report ebitda iva rent m %}</td>
			{% endfor %}
			<td>{% get_total_income report ebitda iva rent months %}</td>
			<td class="bg-secondary">{{last_ebdita_totals|key:'net'}}</td>
			<td>{% get_var_total_income report ebitda iva rent months last_ebdita_totals %}</td>
		</tr>
	</tbody>
</table>